import { useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Feather, ArrowRight } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { errorMessage } from '../api/articles';
export function LoginPage(){return <AuthForm registerMode={false}/>;}
export function RegisterPage(){return <AuthForm registerMode/>;}
function AuthForm({registerMode}:{registerMode:boolean}) {
  const auth=useAuth();const navigate=useNavigate();
  const [name,setName]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[age,setAge]=useState('');
  const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{if(registerMode)await auth.register(name,email,Number(age),password);else await auth.login(email,password);navigate('/journal');}catch(err){setError(errorMessage(err,registerMode?'Couldn’t create your account. Please try again.':'Couldn’t sign in. Check your email and password.'));}finally{setBusy(false);}};
  return <main className="auth-editorial"><aside className="auth-story"><Link className="wordmark" to="/articles"><Feather size={26}/>novelist.</Link><div><p className="eyebrow">A home for your next chapter</p><h1>Read widely.<br/>Think deeply.<br/><em>Write freely.</em></h1><p>Gather the stories that move you.<br/>Make room for the ones you’ll tell.</p></div><Link className="text-link" to="/articles">Explore the journal <ArrowRight size={16}/></Link></aside><section className="auth-form-panel"><p className="eyebrow">{registerMode?'Begin your reading life':'Your notebook is waiting'}</p><h2>{registerMode?'Start your story.':'Welcome back.'}</h2><p className="intro-copy">{registerMode?'A space for your reading, writing, and everything in between.':'Sign in to pick up where you left off.'}</p>{error&&<p className="notice-error" role="alert">{error}</p>}<form className="editorial-form" onSubmit={submit}><fieldset disabled={busy}>{registerMode&&<label>Your name<input value={name} maxLength={100} onChange={e=>setName(e.target.value)} autoComplete="name" required/></label>}<label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={registerMode?8:undefined} maxLength={128} autoComplete={registerMode?'new-password':'current-password'} required/></label>{registerMode&&<label>Age<input type="number" min={0} max={150} value={age} onChange={e=>setAge(e.target.value)} required/></label>}<button className="ink-button" disabled={busy}>{busy?'One moment…':registerMode?'Create your account':'Sign in'}<ArrowRight size={16}/></button></fieldset></form><p className="auth-switch">{registerMode?'Already have an account?':'New to Novelist?'} <Link to={registerMode?'/login':'/register'}>{registerMode?'Sign in':'Start your story'}</Link></p></section></main>;
}
