import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Search, ArrowRight } from 'lucide-react';
import { ragApi } from '../api/rag';
import type { RagChunk } from '../api/types';
import { PageHeading } from '../components/Editorial';
export function ChatPage(){
  const[input,setInput]=useState('');const[submitted,setSubmitted]=useState('');const[results,setResults]=useState<RagChunk[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const search=async(event:FormEvent)=>{event.preventDefault();if(!input.trim()||busy)return;setBusy(true);setError('');setSubmitted(input.trim());try{setResults((await ragApi.search(input.trim(),5)).results);}catch{setResults([]);setError('Search couldn’t complete. Please try again; book content must be indexed before it can be searched.');}finally{setBusy(false);}};
  return <section className="semantic-page"><PageHeading eyebrow="Between the lines" title="Find the passage you’re looking for.">Search the meaning inside indexed books. Explore passages and follow the words back to their source.</PageHeading><form className="semantic-form" onSubmit={search}><label className="sr-only" htmlFor="semantic-query">Search book passages</label><Search size={21}/><input id="semantic-query" value={input} maxLength={500} onChange={e=>setInput(e.target.value)} placeholder="A theme, a feeling, a question…"/><button className="ink-button" disabled={busy||!input.trim()}>{busy?'Searching…':'Find passages'}<ArrowRight size={16}/></button></form><p className="small-note">Semantic search returns excerpts, not generated answers. Only indexed content is included.</p><div className="search-prompts">{['Finding courage in uncertainty','The meaning of belonging','A new beginning'].map(prompt=><button className="outline-button" key={prompt} onClick={()=>setInput(prompt)}>{prompt}</button>)}</div>{error?<p className="notice-error" role="alert">{error}</p>:busy?<div className="editorial-empty" role="status">Looking through the pages…</div>:submitted?<><div className="section-rule"><span>{results.length} passages</span><span>For “{submitted}”</span></div>{results.length?results.map((r,i)=><article className="passage" key={`${r.bookId}-${r.chunkIndex}-${i}`}><p className="eyebrow">Passage {i+1} · Similarity {Math.round(r.score*100)}%</p><blockquote>{r.text}</blockquote><Link className="text-link" to={`/books/${r.bookId}`}>{r.title} · {r.author}<ArrowRight size={15}/></Link></article>):<div className="editorial-empty"><h2>No passages yet.</h2><p>Try a different theme, or add and index book content from a book’s detail page.</p><Link className="text-link" to="/books">Visit the library <ArrowRight size={15}/></Link></div>}</>:null}</section>;
}
