from typing import Protocol

class ArticleRepositoryPort(Protocol):
    def save_article(self, article_id: str, user_id: str, payload: dict) -> dict: ...
    def get_article(self, article_id: str, owner_id: str | None = None) -> dict: ...
    def page_articles(self, page: int, size: int, owner_id: str | None = None, author_id: str | None = None) -> tuple[list[dict], int]: ...
    def get_author(self, user_id: str) -> dict: ...
