"""Outbound dependencies required by rating use cases."""
from typing import Any, Protocol


class RatingRepositoryPort(Protocol):
    def add_rating(self, user_id: str, book_id: str, rating: int, review: str | None) -> dict[str, Any]: ...
    def book_reviews(self, book_id: str) -> list[dict[str, Any]]: ...
    def user_rated_books(self, user_id: str, page: int, size: int) -> tuple[list[dict[str, Any]], int]: ...
